// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/vue-next/pull/3399

declare module 'vue' {
  export interface GlobalComponents {
    AkarIconsCircleCheckFill: typeof import('~icons/akar-icons/circle-check-fill')['default']
    Demo: typeof import('./components/demo/demo.vue')['default']
    Demo2: typeof import('./components/demo2/demo2.vue')['default']
    IconAccountBox: typeof import('~icons/ic/on-account-box')['default']
  }
}

export { }
